// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpeitqmwmikajqrwockb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwZWl0cW13bWlrYWpxcndvY2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTc4MTIsImV4cCI6MjA2NTE3MzgxMn0.ak0pj3bQnYXEMXh8kkiqrQg2Z7oLGSlHZPrzmYfv50o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);